POST {{context_path}}/members/signup
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "faasdfasdfsadf"
}

###

POST {{context_path}}/members/signin
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "faasdfasdfsadf"
}
